# 		Author: Adrian Golias
# Adapted from: http://flask.pocoo.org/
# 				http://flask.pocoo.org/docs/0.12/patterns/fileuploads/

# Importing flask libraries
import flask as fl
from flask import render_template, g, request, redirect, url_for
# Importing other libraries
import os
import re
import base64
#import cStringIO
import keras as kr
import numpy as np
from io import StringIO
from PIL import Image

app = fl.Flask(__name__)

APP_ROOT_DIR = os.path.dirname(os.path.abspath("__file__"))
print(APP_ROOT_DIR)

# Loading trained model that was generated by train.py
model = kr.models.load_model("model.h5")

@app.route("/hook", methods=["POST"])
def get_image():
    image_b64 = request.values['imageBase64']
    image_data = re.sub("^data:image/.+;base64,", "", image_b64).decode("base64")
    image_PIL = Image.open(cStringIO.StringIO(image_b64))
    image_np = np.array(image_PIL)
    print ("Image received: {}".format(image_np.shape))
    return ("")

# Web application template function, which renders index 
# file and runs it on port: 5000 (localhost:5000)
@app.route("/")
def name():
	#return render_template("index.html")
	return app.send_static_file('index.html')



# Upload function, which allows uploading of files to
# rendered web application
@app.route("/upload", methods=['POST'])
def upload_file():
	target = os.path.join(APP_ROOT_DIR, "uploads/")
	print(target)
	
	for file in request.files.getlist("file"):
		print(file)
		filename = file.filename
		destination ="/".join({target,filename})
		print(destination)
		file.save(destination)
		
		return str("File Uploaded Successfully")

if __name__ == '__main__':
	# run our app on localhost:5000
	app.run(host='127.0.0.1', port=5000, debug=True)