# 		Author: Adrian Golias
# Adapted from: http://flask.pocoo.org/
# 				http://flask.pocoo.org/docs/0.12/patterns/fileuploads/

# Importing flask libraries
import flask as fl
from flask import render_template, g, request, redirect, url_for
# Importing other libraries
import os
import keras as kr

app = fl.Flask(__name__)

APP_ROOT_DIR = os.path.dirname(os.path.abspath("__file__"))
print(APP_ROOT_DIR)

# Loading trained model that was generated by train.py
model = kr.models.load_model("model.h5")

# Web application template function, which renders index 
# file and runs it on port: 5000 (localhost:5000)
@app.route("/")
def name():
	return render_template("Index.html")

# Upload function, which allows uploading of files to
# rendered web application
@app.route("/upload", methods=['POST'])
def upload_file():
	target = os.path.join(APP_ROOT_DIR, "uploads/")
	print(target)
	
	for file in request.files.getlist("file"):
		print(file)
		filename = file.filename
		destination ="/".join({target,filename})
		print(destination)
		file.save(destination)
		
		return str("File Uploaded Successfully")

if __name__ == '__main__':
	app.run(host="0.0.0.0", port=5000, debug=True)

    

